networks:
  testnet:
    ipam:
      config:
        - subnet: 172.23.0.0/24
  
services:
  changeletters:
    build:
      context: ../
      dockerfile: ChangeLetters/Dockerfile
    networks:
      - testnet
    ports:
      - "18080:8080"
      - "18081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_URLS: "http://0.0.0.0:8080;https://0.0.0.0:8081"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetcore.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: MyPassword
      DataDirectory: /tmp/data
      ConnectionStrings__Sqlite: Data Source=/tmp/data/ChangeLetters.db;
      OpenAi__UseOpenAi: "false"
      Alive__IsActive: "true"
      Alive__IntervalSeconds: 5
      Logging__LogLevel__Default: Trace
      Logging__LogLevel__FluentFTP: Trace
      Logging__LogLevel__Microsoft__AspNetCore: Trace
      Logging__LogLevel__Microsoft__EntityFrameworkCore: Trace
    volumes:
      - ../ChangeLetters.IntegrationTests/https:/https
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ftp-server:
    image: garethflowers/ftp-server
    networks:
      testnet:
        ipv4_address: 172.23.0.10
    container_name: ftp-server
    entrypoint: ["/bin/sh","-c","set -e; mkdir -p /home/myuser/working && exec /docker-entrypoint.sh /usr/sbin/vsftpd /etc/vsftpd.conf"]
    ports:
      - "2121:21"
      - "40000-40010:40000-40010" # For passive mode
    environment:
      FTP_USER: "myuser"
      FTP_PASS: "mypass"    
      PUBLIC_IP: "host.docker.internal" # Use the service name for internal Docker networking
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  # filezilla:
  #   image: jlesage/filezilla
  #   networks:
  #     - testnet
  #   ports:
  #     - "5800:5800"
  #   environment:
  #     - TZ=Europe/Berlin
  #     - USER_ID=1000
  #     - GROUP_ID=1000
  #   volumes:
  #     - C:/temp/ftp-client/filezilla:/config:rw
  #     - C:/temp/ftp-client/files:/storage:rw