services:
  changeletters:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2121:2121"
      - "21:21"
      - "40000-40009:40000-40009/tcp" # For FTP passive mode
      - "49000-50000:49000-50000" # Visual Studio debugging
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetcore.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: MyPassword
      DataDirectory: /data
      ConnectionStrings__Sqlite: Data Source=/data/ChangeLetters.db;