//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeLetters.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeLetters.Tests.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Pr?sidenten&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;B?ttcher&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Zur?ck&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Shitb?rgertum&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Sch?ner&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Kv?ven&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Aufz?gen&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Au?enposten&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;M?nner&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;W?r&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Million?r&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;F?r&quot;
        /// },
        /// {
        ///  &quot;UnknownWord&quot;: &quot;Plan?nderung&quot;
        /// },
        /// {
        ///  &quot;UnknownWo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fiftyUnknownWords {
            get {
                return ResourceManager.GetString("fiftyUnknownWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;M?bius&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Möbius&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;Ungek?rzt&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Ungekürzt&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;Verm?chtnis&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Vermächtnis&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;?ber&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Über&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;B?sen&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Bösen&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;Unterst?tzt&quot;,
        ///    &quot;CorrectedWord&quot;: &quot;Unterstützt&quot;
        ///  },
        ///  {
        ///    &quot;UnknownWord&quot;: &quot;Kalenderm?dchen&quot;,
        ///    &quot;Correcte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
    }
}
