// <auto-generated />
using System;
using ChangeLetters.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeLetters.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250826130238_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("ChangeLetters.Models.VocabularyItem", b =>
                {
                    b.Property<Guid>("VocabularyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnknownWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VocabularyItemId");

                    b.ToTable("VocabularyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
