name: Build and Test (.NET)

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call: {} 
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./source/ChangeLetters.sln 

      - name: Build
        run: dotnet build ./source/ChangeLetters.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./source/ChangeLetters.sln --no-build --configuration Release --collect:"XPlat Code Coverage"