name: CI on Merge (build + integration tests)

on:
  push:
    branches:
      - main
      - feature/**      
  workflow_dispatch:

env:
  COMPOSE_PROJECT_NAME: changeletters_itests  # use changeletters_itests_testnet defined in docker-compose.yml

jobs:
  # 1) call existing build-and-test.yml auf
  build_and_unit_tests:
    uses: ./.github/workflows/build-and-test.yml

  # 2) Integration tests against docker-compose
  integration_tests:
    name: Integration Tests (docker-compose)
    runs-on: ubuntu-latest
    needs: build_and_unit_tests
    defaults:
      run:
        working-directory: ./source/ChangeLetters.IntegrationTests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Compose up (fresh build)
        run: |
          docker compose down -v || true
          docker compose up -d --build --force-recreate

      - name: Wait for FTP (Port 21) to be ready
        run: |
          set -e
          NET="${COMPOSE_PROJECT_NAME}_testnet"
          for i in $(seq 1 20); do
            if docker run --rm --network "$NET" alpine sh -c 'apk add -q --no-progress busybox-extras >/dev/null 2>&1 || true; nc -zv -w 1 172.23.0.10 21'; then
              echo "FTP server running"
              break
            fi
            echo "Waiting for FTP server ($i/20)"
            sleep 1
          done

      - name: Run integration tests
        run: |
          dotnet test ./ChangeLetters.IntegrationTests.sln \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: ./source/ChangeLetters.IntegrationTests/TestResults

      - name: Collect container logs
        if: always()
        shell: bash
        env:
          PROJECT: "${{ env.COMPOSE_PROJECT_NAME }}"
        run: |
          set -Eeuo pipefail
          mkdir -p logs
          docker ps -a > logs/compose-ps.txt || true
          docker compose ls > logs/compose-ls.txt || true
          BASE_FILTER="label=com.docker.compose.service"
          PROJ_FILTER=""
          if [ -n "$PROJECT" ]; then
            PROJ_FILTER="--filter label=com.docker.compose.project=$PROJECT"
          fi
          FTP_ID=$(docker ps -q $PROJ_FILTER --filter "$BASE_FILTER=ftp-server" || true)
          APP_ID=$(docker ps -q $PROJ_FILTER --filter "$BASE_FILTER=changeletters" || true)
          echo "FTP_ID=${FTP_ID}"        | tee -a logs/_ids.txt
          echo "APP_ID=${APP_ID}"        | tee -a logs/_ids.txt
          echo "PROJECT=${PROJECT}"      | tee -a logs/_ids.txt
          # Alle Compose-Logs (falls compose-Files greifbar sind)
          docker compose logs --no-color > logs/compose-all.log 2>&1 || true
          # Einzel-Logs + Inspect + wichtige Dateien
          if [ -n "$FTP_ID" ]; then
            docker logs --timestamps "$FTP_ID" > logs/ftp-server.log 2>&1 || true
            docker inspect "$FTP_ID" > logs/ftp-server.inspect.json 2>&1 || true
            docker exec "$FTP_ID" sh -c 'cat /etc/vsftpd.conf 2>/dev/null || true' > logs/ftp-server.vsftpd.conf 2>&1 || true
          fi
          if [ -n "$APP_ID" ]; then
            docker logs --timestamps "$APP_ID" > logs/changeletters.log 2>&1 || true
            docker inspect "$APP_ID" > logs/changeletters.inspect.json 2>&1 || true
          fi
          [ -s logs/compose-all.log ] || echo "no logs" > logs/EMPTY.txt
          # Compose-Dateien mit sichern (falls vorhanden)
          [ -f docker-compose.yml ] && cp docker-compose.yml logs/ || true
          [ -f docker-compose.ci.yml ] && cp docker-compose.ci.yml logs/ || true

      - name: Upload container logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: logs/**
     
      - name: Compose down (cleanup)
        if: always()
        run: docker compose down -v
