name: CI on Merge (build + integration tests)

on:
  push:
    branches:
      - main
      - feature/**      
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  
env:
  COMPOSE_PROJECT_NAME: changeletters_itests  # use changeletters_itests_testnet defined in docker-compose.yml

jobs:
  # 1) call existing build-and-test.yml auf
  build_and_unit_tests:
    uses: ./.github/workflows/build-and-test.yml

  # 2) Integration tests against docker-compose
  integration_tests:
    name: Integration Tests (docker-compose)
    runs-on: ubuntu-latest
    needs: build_and_unit_tests
    defaults:
      run:
        working-directory: ./source/ChangeLetters.IntegrationTests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Compose up (fresh build)
        run: |
          docker compose down -v || true
          docker compose up -d --build --force-recreate

      - name: Wait for FTP (Port 21) to be ready
        run: |
          set -e
          NET="${COMPOSE_PROJECT_NAME}_testnet"
          for i in $(seq 1 20); do
            if docker run --rm --network "$NET" alpine sh -c 'apk add -q --no-progress busybox-extras >/dev/null 2>&1 || true; nc -zv -w 1 172.23.0.10 21'; then
              echo "FTP server running"
              break
            fi
            echo "Waiting for FTP server ($i/20)"
            sleep 1
          done
          
      - name: Ensure host.docker.internal resolves on runner
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          getent hosts host.docker.internal
          
      - name: Set FTP env for tests
        run: |
          echo "FTP_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "FTP_PORT=2121" >> $GITHUB_ENV
          
      - name: Smoke test FTP (login + list)
        run: |
          apk add --no-progress curl >/dev/null 2>&1 || true
          curl -v --user myuser:mypass "ftp://127.0.0.1:2121/" || exit 1
          
      - name: Run integration tests
        run: |
          dotnet test ./ChangeLetters.IntegrationTests.sln \
            --settings ./.runsettings \
            --configuration Release \
            --logger "console;verbosity=detailed" \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults
            
      - name: List TRX files (debug)
        if: always()
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -lah "$GITHUB_WORKSPACE/source/ChangeLetters.IntegrationTests/TestResults" || true
          echo "Find any *.trx near TestResults:"
          find "$GITHUB_WORKSPACE/source/ChangeLetters.IntegrationTests" -maxdepth 3 -name "*.trx" -print || true

      - name: Publish test summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Integration Tests
          path: ./source/ChangeLetters.IntegrationTests/TestResults/*.trx
          reporter: dotnet-trx
          fail-on-error: false
          list-suites: all
          list-tests: all
          only-summary: false
          fail-on-empty: true
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: ./source/ChangeLetters.IntegrationTests/TestResults

      - name: Collect container logs
        if: always()
        shell: bash
        env:
          PROJECT: "${{ env.COMPOSE_PROJECT_NAME }}"
        run: |
          set -Eeuo pipefail
          LOGDIR="${GITHUB_WORKSPACE}/logs"
          mkdir -p "${LOGDIR}"
          docker ps -a > ${LOGDIR}/compose-ps.txt || true
          docker compose ls > ${LOGDIR}/compose-ls.txt || true
          BASE_FILTER="label=com.docker.compose.service"
          PROJ_FILTER=""
          if [ -n "$PROJECT" ]; then
            PROJ_FILTER="--filter label=com.docker.compose.project=$PROJECT"
          fi
          FTP_ID=$(docker ps -q $PROJ_FILTER --filter "$BASE_FILTER=ftp-server" || true)
          APP_ID=$(docker ps -q $PROJ_FILTER --filter "$BASE_FILTER=changeletters" || true)
          printf "FTP_ID=%s\nAPP_ID=%s\nPROJECT=%s\n" "${FTP_ID}" "${APP_ID}" "${PROJECT:-}" | tee -a "${LOGDIR}/_ids.txt"
          # Alle Compose-Logs (falls compose-Files greifbar sind)
          docker compose logs --no-color > ${LOGDIR}/compose-all.log 2>&1 || true
          # Einzel-Logs + Inspect + wichtige Dateien
          if [ -n "$FTP_ID" ]; then
            docker logs --timestamps "$FTP_ID" > ${LOGDIR}/ftp-server.log 2>&1 || true
            docker inspect "$FTP_ID" > ${LOGDIR}/ftp-server.inspect.json 2>&1 || true
            docker exec "$FTP_ID" sh -c 'cat /etc/vsftpd.conf 2>/dev/null || true' > ${LOGDIR}/ftp-server.vsftpd.conf 2>&1 || true
          fi
          if [ -n "$APP_ID" ]; then
            docker logs --timestamps "$APP_ID" > ${LOGDIR}/changeletters.log 2>&1 || true
            docker inspect "$APP_ID" > ${LOGDIR}/changeletters.inspect.json 2>&1 || true
          fi
          [ -s ${LOGDIR}/compose-all.log ] || echo "no logs" > ${LOGDIR}/EMPTY.txt
          # Compose-Dateien mit sichern (falls vorhanden)
          [ -f docker-compose.yml ] && cp docker-compose.yml ${LOGDIR}/ || true
          [ -f docker-compose.ci.yml ] && cp docker-compose.ci.yml ${LOGDIR}/ || true

      - name: Upload container logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: logs/**
     
      - name: Compose down (cleanup)
        if: always()
        run: docker compose down -v
