name: Start integration tests

on:
  push:
    branches:
      - main     
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
        
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_and_unit_tests:
    uses: ./.github/workflows/build-and-test-runner.yml
    
  integration_tests:
    needs: build_and_unit_tests 
    uses: ./.github/workflows/integration-runner.yml

