name: Create Tag

on:
  workflow_dispatch:

permissions:
  checks: write
  issues: write
  contents: write
  pull-requests: write

jobs:

  build_and_unit_tests:
    uses: ./.github/workflows/resuable-build-and-test.yml

  integration_tests:
    needs: build_and_unit_tests
    uses: ./.github/workflows/resuable-integration-tests.yml

  create_prerelease_version_tag:
    name: Tag Version
    needs: [build_and_unit_tests, integration_tests]
    uses: ./.github/workflows/resuable-create-tag.yml
