name: Release

on:
  workflow_run:
    workflows: ["Integration tests"]
    types:
      - completed
    branches:
      - main          
  workflow_dispatch:
  
jobs:
  create-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install semantic-release and plugins
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release