name: Develop Pull Action

on:
  push:
    branches:
      - develop

permissions:
  checks: write
  issues: write
  contents: write
  pull-requests: write

jobs:

  build_and_unit_tests:
    uses: ./.github/workflows/resuable-build-and-test.yml

  integration_tests:
    needs: build_and_unit_tests
    uses: ./.github/workflows/resuable-integration-tests.yml

  create_prerelease_version_tag:
    name: Calculate & Tag Prerelease Version
    needs: [build_and_unit_tests, integration_tests]
    uses: ./.github/workflows/resuable-create-prerelease-tag.yml