name: PR Develop Integration Tests

on:
  push:
    branches:
      - develop      
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
        
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_and_unit_tests:
    uses: ./.github/workflows/resuable-build-and-test.yml
    
  integration_tests:
    needs: build_and_unit_tests 
    uses: ./.github/workflows/resuable-integration-tests.yml

